version: "3.12"

services:
  web:
    build:
      context: .
    ports: 
      - "8000:8000"
    command: ["sh", "./start.sh"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres_db #the container that i'm goind to run
    
  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    

volumes:
  postgres_data:
    # Define options for the volume o make it presistent
    # for example: 
    driver: local
