pipeline {
    agent {
        docker {
            image 'python:3.12' // Use a Python Docker image
            args '-u root' // Run as root to install dependencies
        }
    }
    environment {
        DB_NAME = 'mydatabase' // credentials('DB_NAME') 
        DB_USER = 'ahmed' // credentials('DB_USER') 
        DB_PASS = 'Ahmed123' // credentials('DB_PASS')
    }
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/AhMeD7493/My-Django-Project.git' // Replace with your repo URL
            }
        }
        stage('Build Docker Images') {
            steps {
                script {
                    // Build the Django app image
                    sh 'docker compose build'
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    // Run your tests
                    sh 'docker compose run web python manage.py test'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // Bring up the containers
                    sh 'docker compose up -d'
                }
            }
        }
    }
    post {
        always {
            // Clean up
            script {
                sh 'docker compose down'
            }
        }
    }
}

